<template>
  <div class="sb-py-10">
    <div>
      <h2 class="sb-text-2xl sb-font-bold sb-mb-5">
        Cash Flow Indicator Ratios
      </h2>
      <div class="sb-flex sb-py-4 sb-border-2 sb-border-gray-200 sb-px-3 sb-bg-gray-100">
        <div class="sb-w-1/12 sb-text-sm">
          Operating Cash Flow Sales Ratio
        </div>
        <div class="sb-w-5/12 sb-text-[12px]">
          <vue-mathjax formula="$$ OperatingCashFlow \over Revenue $$" />
        </div>
        <div class="sb-w-1/12 sb-text-sm sb-text-center">
          {{ financialRatios.operatingCashFlowSalesRatioTTM | formatNumber }}
        </div>
        <div class="sb-w-5/12 sb-text-sm">
          Gives investors an idea of the company's ability to turn sales into cash.
        </div>
      </div>
      <div class="sb-flex sb-py-4 sb-border-2 sb-border-t-0 sb-border-gray-200 sb-px-3">
        <div class="sb-w-1/12 sb-text-sm">
          Free Cash Flow Operating Cash Flow Ratio
        </div>
        <div class="sb-w-5/12 sb-text-[12px]">
          <vue-mathjax formula="$$ FreeCashFlow \over OperatingCashFlow $$" />
        </div>
        <div class="sb-w-1/12 sb-text-sm sb-text-center">
          {{ financialRatios.freeCashFlowOperatingCashFlowRatioTTM | formatNumber }}
        </div>
        <div class="sb-w-5/12 sb-text-sm">
          The higher the percentage of free cash flow embedded in a company's operating cash flow, the greater the financial strength of the company.
        </div>
      </div>
      <div class="sb-flex sb-py-4 sb-border-2 sb-border-t-0 sb-border-gray-200 sb-px-3 sb-bg-gray-100">
        <div class="sb-w-1/12 sb-text-sm">
          Cash Flow Coverage Ratios
        </div>
        <div class="sb-w-5/12 sb-text-[12px]">
          <vue-mathjax formula="$$ OperatingCashFlow \over TotalDebt $$" />
        </div>
        <div class="sb-w-1/12 sb-text-sm sb-text-center">
          {{ financialRatios.cashFlowCoverageRatiosTTM | formatNumber }}
        </div>
        <div class="sb-w-5/12 sb-text-sm">
          The operating cash flow is simply the amount of cash generated by the company from its main operations, which are used to keep the business funded.
        </div>
      </div>
      <div class="sb-flex sb-py-4 sb-border-2 sb-border-t-0 sb-border-gray-200 sb-px-3">
        <div class="sb-w-1/12 sb-text-sm">
          Short-Term Coverage Ratios
        </div>
        <div class="sb-w-5/12 sb-text-[12px]">
          <vue-mathjax formula="$$ OperatingCashFlow \over Short − TermDebt $$" />
        </div>
        <div class="sb-w-1/12 sb-text-sm sb-text-center">
          {{ financialRatios.shortTermCoverageRatiosTTM | formatNumber }}
        </div>
        <div class="sb-w-5/12 sb-text-sm">
          The short-term debt coverage ratio compares the sum of a company's short-term borrowings and the current portion of its long-term debt to operating cash flow.
        </div>
      </div>
      <div class="sb-flex sb-py-4 sb-border-2 sb-border-t-0 sb-border-gray-200 sb-px-3 sb-bg-gray-100">
        <div class="sb-w-1/12 sb-text-sm">
          Capital Expenditure Coverage Ratios
        </div>
        <div class="sb-w-5/12 sb-text-[12px]">
          <vue-mathjax formula="$$ OperatingCashFlow \over CapitalExpenditure $$" />
        </div>
        <div class="sb-w-1/12 sb-text-sm sb-text-center">
          {{ financialRatios.capitalExpenditureCoverageRatioTTM | formatNumber }}
        </div>
        <div class="sb-w-5/12 sb-text-sm">
          The larger the operating cash flow coverage for these items, the greater the company's ability to meet its obligations, along with giving the company more cash flow to expand its business, withstand hard times, and not be burdened by debt servicing and the restrictions typically included in credit agreements.
        </div>
      </div>
      <div class="sb-flex sb-py-4 sb-border-2 sb-border-t-0 sb-border-gray-200 sb-px-3">
        <div class="sb-w-1/12 sb-text-sm">
          Dividend Paid and Capex Coverage Ratios
        </div>
        <div class="sb-w-5/12 sb-text-[12px]">
          <vue-mathjax formula="$$ OperatingCashFlow \over DividendPaid + CapitalExpenditure $$" />
        </div>
        <div class="sb-w-1/12 sb-text-sm sb-text-center">
          {{ financialRatios.dividendPaidAndCapexCoverageRatioTTM | formatNumber }}
        </div>
        <div class="sb-w-5/12 sb-text-sm">
          For conservative investors focused on cash flow coverage, comparing the sum of a company's capital expenditures and cash dividends to its operating cash flow is a stringent measurement that puts cash flow to the ultimate test. If a company is able to cover both of these outlays of funds from internal sources and still have cash left over, it is producing what might be called "free cash flow on steroids". This circumstance is a highly favorable investment quality.
        </div>
      </div>
      <div class="sb-flex sb-py-4 sb-border-2 sb-border-t-0 sb-border-gray-200 sb-px-3 sb-bg-gray-100">
        <div class="sb-w-1/12 sb-text-sm">
          Dividend Payout Ratio
        </div>
        <div class="sb-w-5/12 sb-text-[12px]">
          <vue-mathjax formula="$$ DPS(DividendperShare) \over EPS(NetIncomeperShareNumber $$" />
        </div>
        <div class="sb-w-1/12 sb-text-sm sb-text-center">
          -
        </div>
        <div class="sb-w-5/12 sb-text-sm">
          The dividend payout ratio is an indicator of how well earnings support the dividend payment.
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from '@nuxtjs/composition-api'
import { StockFinancialRatios } from '~/models/stock-prices.model'

export default defineComponent({
  name: 'CashFlowIndicatorRatios',

  filters: {
    formatNumber: (value: number) => {
      return value ? value.toFixed(2) : '-'
    }
  },

  props: {
    financialRatios: {
      type: Object as () => StockFinancialRatios,
      required: true
    }
  }
})
</script>
